# Generated by Django 3.0.7 on 2020-07-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='code',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
    ]
