# Generated by Django 3.0.7 on 2020-07-17 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_accounts_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_received', to='manager.Accounts'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_sent', to='manager.Accounts'),
        ),
    ]
